name: chatbot_ui_agribot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  google_fonts: ^8.0.1
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.1
  uuid: ^4.5.3
  webview_flutter: ^4.13.1
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/step1.png
    - assets/images/step2.png
    - assets/images/step3.png
    - assets/images/step4.png
